config/routes.rb
Rails.application.routes.draw do
  resources :questions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Errors Routes
  match '/403', to: 'errors#forbidden', via: [:delete, :get, :patch, :post, :put], as: :forbidden
  match '/404', to: 'errors#file_not_found', via: [:delete, :get, :patch, :post, :put], as: :file_not_found
  match '/422', to: 'errors#unprocessable', via: [:delete, :get, :patch, :post, :put], as: :unprocessable
  match '/500', to: 'errors#internal_server_error', via: [:delete, :get, :patch, :post, :put], as: :internal_server_error

  # Locale Scope
  scope 'locale' do
    get 'change/:country' => 'localize#change', as: :locale_change
    get 'states_from/:country' => 'localize#states_from', as: :states_from
    get 'cities_from/:country/:state' => 'localize#cities_from', as: :cities_from
  end

  # DeviseUser sessions
  devise_for :users,
             controllers: {
               unlocks: 'users/unlocks',
               sessions: 'users/sessions',
               passwords: 'users/passwords',
               registrations: 'users/registrations',
               confirmations: 'users/confirmations',
               omniauth_callbacks: 'users/omniauth_callbacks'
             }

  # Not Persistence actions
  get 'dashboard' => 'dashboard#index', as: :dashboard
  get 'recent_videos' => 'dashboard#recent', as: :recent_videos
  get '/users/delete_account' => 'profiles#delete_account', as: :delete_account
  get '/terms' => 'terms#index', as: :terms
  get '/policy' => 'terms#policy', as: :policy

  # Persistence Actions
  resources :roles
  resources :profiles
  # resources :experiences
  resources :subscriptions, only: [:new, :create]
  resources :courses do
    # resources :admin_courses
    resources :periods do
      resources :lessons
    end
  end

  # Root route
  # root to: 'dashboard#index'
  root to: 'dashboard#recent'
end

app/models/question.rb
class Question < ApplicationRecord
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[ show edit update destroy ]

  # GET /questions or /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1 or /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions or /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: "Question was successfully created." }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: "Question was successfully updated." }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: "Question was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:name, :target, :options)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.slim
= form_for @question do |f|
  - if @question.errors.any?
    #error_explanation
      h2 = error_msg(@question)
      ul
        - @question.errors.full_messages.each do |message|
          li = message

  .row
    .col-md-12.col-sm-12
      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control'
  .row
    .col-md-12.col-sm-12
      .form-group
        = f.label :target
        = f.text_field :target, class: 'form-control'
  .row
    .col-md-12.col-sm-12
      .form-group
        = f.label :options
        = f.text_field :options, class: 'form-control'


  = f.submit class: 'btn btn-success btn-fill pull-right'
  .clearfix

app/views/questions/edit.html.slim
h1 Editing question

== render 'form'

=> link_to 'Show', @question
'|
=< link_to 'Back', questions_path

app/views/questions/index.html.slim
.container-fluid
  .row
    table.smart-table.table.col-md-12.col-xs-12
      thead
        tr
          th =t('activerecord.attributes.question.name')
          th =t('activerecord.attributes.question.options')
          th =t('activerecord.attributes.question.target')
          th
          th
          th

      tbody
        - @questions.each do |question|
          tr
            td = question.name
            td = question.options
            td = question.target
            td =link_to question_path(question) do
              i.fa.fa-eye
            td =link_to edit_question_path(question) do
              i.fa.fa-edit
            td =link_to question, data: {confirm: 'Você tem certeza de que deseja deletar este registro?'}, method: :delete do
              i.fa.fa-trash.text-danger

app/views/questions/new.html.slim
= render 'form'
= link_to t('actions.questions.index'), questions_path

app/views/questions/show.html.slim
p#notice = notice

p
  strong Name:
  = @question.name
p
  strong Target:
  = @question.target
p
  strong Options:
  = @question.options

=> link_to 'Edit', edit_question_path(@question)
'|
=< link_to 'Back', questions_path