config/routes.rb
Rails.application.routes.draw do
  resources :questions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Errors Routes
  match '/403', to: 'errors#forbidden', via: [:delete, :get, :patch, :post, :put], as: :forbidden
  match '/404', to: 'errors#file_not_found', via: [:delete, :get, :patch, :post, :put], as: :file_not_found
  match '/422', to: 'errors#unprocessable', via: [:delete, :get, :patch, :post, :put], as: :unprocessable
  match '/500', to: 'errors#internal_server_error', via: [:delete, :get, :patch, :post, :put], as: :internal_server_error

  # Locale Scope
  scope 'locale' do
    get 'change/:country' => 'localize#change', as: :locale_change
    get 'states_from/:country' => 'localize#states_from', as: :states_from
    get 'cities_from/:country/:state' => 'localize#cities_from', as: :cities_from
  end

  # DeviseUser sessions
  devise_for :users,
             controllers: {
               unlocks: 'users/unlocks',
               sessions: 'users/sessions',
               passwords: 'users/passwords',
               registrations: 'users/registrations',
               confirmations: 'users/confirmations',
               omniauth_callbacks: 'users/omniauth_callbacks'
             }

  # Not Persistence actions
  get 'dashboard' => 'dashboard#index', as: :dashboard
  get 'recent_videos' => 'dashboard#recent', as: :recent_videos
  get '/users/delete_account' => 'profiles#delete_account', as: :delete_account
  get '/terms' => 'terms#index', as: :terms
  get '/policy' => 'terms#policy', as: :policy

  # Persistence Actions
  resources :roles
  resources :profiles
  # resources :experiences
  resources :subscriptions, only: [:new, :create]
  resources :courses do
    # resources :admin_courses
    resources :periods do
      resources :lessons
    end
  end

  # Root route
  # root to: 'dashboard#index'
  root to: 'dashboard#recent'
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  # Dependencies
  acts_as_paranoid

  # Relations
  belongs_to :user
  belongs_to :course

  # Validations
  validates_presence_of :user
  validates_presence_of :course
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subscription_params
      params.require(:subscription).permit(:last_lesson, :user_id, :course_id)
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.slim
= form_for @subscription do |f|
  - if @subscription.errors.any?
    #error_explanation
      -obj = @subscription
      -if obj.errors.count == 1
        h2 ="#{obj.errors.count} erro #{t('flash.error')}: "
      -else
        h2 ="#{obj.errors.count} erros #{t('flash.errors')}: "

      ul
        -obj.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :last_lesson
    = f.text_field :last_lesson
  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :course
    = f.text_field :course
  .actions = f.submit

app/views/subscriptions/edit.html.slim
h1 Editing subscription

== render 'form'

=> link_to 'Show', @subscription
'|
=< link_to 'Back', subscriptions_path

app/views/subscriptions/index.html.slim
h1 Listing subscriptions

table
  thead
    tr
      th Last lesson
      th User
      th Course
      th
      th
      th

  tbody
    - @subscriptions.each do |subscription|
      tr
        td = subscription.last_lesson
        td = subscription.user
        td = subscription.course
        td = link_to 'Show', subscription
        td = link_to 'Edit', edit_subscription_path(subscription)
        td = link_to 'Destroy', subscription, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Subscription', new_subscription_path

app/views/subscriptions/new.html.slim
h1 New subscription

== render 'form'

= link_to 'Back', subscriptions_path

app/views/subscriptions/show.html.slim
p#notice = notice

p
  strong Last lesson:
  = @subscription.last_lesson
p
  strong User:
  = @subscription.user
p
  strong Course:
  = @subscription.course

=> link_to 'Edit', edit_subscription_path(@subscription)
'|
=< link_to 'Back', subscriptions_path