config/routes.rb
Rails.application.routes.draw do
  resources :questions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Errors Routes
  match '/403', to: 'errors#forbidden', via: [:delete, :get, :patch, :post, :put], as: :forbidden
  match '/404', to: 'errors#file_not_found', via: [:delete, :get, :patch, :post, :put], as: :file_not_found
  match '/422', to: 'errors#unprocessable', via: [:delete, :get, :patch, :post, :put], as: :unprocessable
  match '/500', to: 'errors#internal_server_error', via: [:delete, :get, :patch, :post, :put], as: :internal_server_error

  # Locale Scope
  scope 'locale' do
    get 'change/:country' => 'localize#change', as: :locale_change
    get 'states_from/:country' => 'localize#states_from', as: :states_from
    get 'cities_from/:country/:state' => 'localize#cities_from', as: :cities_from
  end

  # DeviseUser sessions
  devise_for :users,
             controllers: {
               unlocks: 'users/unlocks',
               sessions: 'users/sessions',
               passwords: 'users/passwords',
               registrations: 'users/registrations',
               confirmations: 'users/confirmations',
               omniauth_callbacks: 'users/omniauth_callbacks'
             }

  # Not Persistence actions
  get 'dashboard' => 'dashboard#index', as: :dashboard
  get 'recent_videos' => 'dashboard#recent', as: :recent_videos
  get '/users/delete_account' => 'profiles#delete_account', as: :delete_account
  get '/terms' => 'terms#index', as: :terms
  get '/policy' => 'terms#policy', as: :policy

  # Persistence Actions
  resources :roles
  resources :profiles
  # resources :experiences
  resources :subscriptions, only: [:new, :create]
  resources :courses do
    # resources :admin_courses
    resources :periods do
      resources :lessons
    end
  end

  # Root route
  # root to: 'dashboard#index'
  root to: 'dashboard#recent'
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  # Dependencies
  acts_as_paranoid

  # Relations
  belongs_to :period

  # Validations
  validates :icon, length: { minimum: 5, maximum: 55 }, presence: false
  validates :name, length: { minimum: 5, maximum: 70 }, presence: true
  validates :video_id, length: { minimum: 5, maximum: 70 }, presence: true, on: :update
  validates_presence_of :period
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :check_validated_account
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
      @card_title = @lesson.name
      @card_subtitle = @lesson.description
    end

    # Only allow a list of trusted parameters through.
    def lesson_params
      params.require(:lesson).permit(:name, :video_id, :period_id)
    end

    # if account docs not valid, redirect to profile to update it
    def check_validated_account
      if @current_user.profile.nil? || !@current_user.profile.validated_docs
        n_profile_path = nil
        if @current_user.profile.nil?
          n_profile_path = new_profile_path
        else
          n_profile_path = edit_profile_path(@current_user.profile)
        end

        redirect_to n_profile_path
      end
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.slim
= form_for @lesson do |f|
  - if @lesson.errors.any?
    #error_explanation
      -obj = @lesson
      -if obj.errors.count == 1
        h2 ="#{obj.errors.count} erro #{t('flash.error')}: "
      -else
        h2 ="#{obj.errors.count} erros #{t('flash.errors')}: "

      ul
        -obj.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :video_id
    = f.text_field :video_id
  .field
    = f.label :period
    = f.text_field :period
  .actions = f.submit

app/views/lessons/edit.html.slim
h1 Editing lesson

== render 'form'

=> link_to 'Show', @lesson
'|
=< link_to 'Back', lessons_path

app/views/lessons/index.html.slim
h1 Listing lessons

table
  thead
    tr
      th Name
      th Video url
      th Period
      th
      th
      th

  tbody
    - @lessons.each do |lesson|
      tr
        td = lesson.name
        td = lesson.video_id
        td = lesson.period
        td = link_to 'Show', lesson
        td = link_to 'Edit', edit_lesson_path(lesson)
        td = link_to 'Destroy', lesson, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Lesson', new_lesson_path

app/views/lessons/new.html.slim
h1 New lesson

== render 'form'

= link_to 'Back', lessons_path

app/views/lessons/show.html.slim
.row
  .col-md-3.col-sm-12
    .alert.alert-warning Curtindo nosso vídeo você levará nossas aulas a mais pessoas.
  .col-md-3.col-sm-12.col-xl-6
    /Channel Subscribe
    script src="https://apis.google.com/js/platform.js"
    div class="g-ytsubscribe" data-channelid="UCfsI-F8KtcNFpmxg7zMid-w" data-layout="full" data-count="default"
  .col-md-6.col-sm-12.col-xl-6
    /Like / Dislike buttons
    .col-md-3.col-sm-6.col-xl-6
      button.btn.btn-link.btn-success.btn-icon#like onclick="authenticate().then(loadClient)"
        i.fal.fa-thumbs-up
        = ' Gostei'
    .col-md-3.col-sm-6.col-xl-6
      button.btn.btn-link.btn-success.btn-icon#dislike onclick="authenticate().then(loadClient)"
        i.fal.fa-thumbs-down
        = ' Não gostei'
    / .col-md-3.col-sm-6.col-xl-6
    /   button onclick="execute()" execute
/Video Render
iframe width="100%" height="500" src="https://www.youtube.com/embed/videoseries?list=PLPJvRB7ImtVPzF5BNMKtEVSHKBqt2i9cg" title="#{@card_title}" frameborder="0"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="allowfullscreen"

script src="https://apis.google.com/js/api.js"
javascript:
  /**
   * Sample JavaScript code for youtube.videos.rate
   * See instructions for running APIs Explorer code samples locally:
   * https://developers.google.com/explorer-help/guides/code_samples#javascript
   */
  function authenticate() {
    return gapi.auth2.getAuthInstance()
        .signIn({scope: "https://www.googleapis.com/auth/youtube https://www.googleapis.com/auth/youtube.force-ssl https://www.googleapis.com/auth/youtubepartner"})
        .then(function() { console.log("Sign-in successful"); },
              function(err) { console.error("Error signing in", err); });
  }
  function loadClient() {
    gapi.client.setApiKey("#{NENV['YT_GOOGLE_API_KEY']}");
    return gapi.client.load("https://content.googleapis.com/discovery/v1/apis/youtube/v3/rest")
        .then(function() { console.log("GAPI client loaded for API"); },
              function(err) { console.error("Error loading GAPI client for API", err); });
  }
  // Make sure the client is loaded and sign-in is complete before calling this method.
  function execute(videoId, type) {
    if(!type) type = "like"
    return gapi.client.youtube.videos.rate({
      "id": videoId,
      "rating": type
    })
        .then(function(response) {
                // Handle the results here (response.result has the parsed body).
                console.log("Response", response);
              },
              function(err) { console.error("Execute error", err); });
  }
  gapi.load("client:auth2", function() {
    gapi.auth2.init({client_id: "#{NENV['YT_GOOGLE_CLIENT_ID']}"});
  });